project:
  type: website
  output-dir: docs

website:
  title: "Joey Larabee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: media.qmd
        text: Media
      - href: portfolio.qmd
        text: Project Portfolio

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full



